### ISSUE TITLE
[Error]: 发送本地图片时抛出 KeyError('json')

### ISSUE THREAD

**Issue by cutekibry** [GraiaProject/Application#134]
**描述你遇到的问题:**
发送本地图片时抛出 `KeyError('json')`。

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 创建任意一张 `.jpg` 格式图片，命名为 `1.jpg`
2. 在同目录下运行下面的代码

**发生错误的代码**

```python3
from graia.application.event.lifecycle import ApplicationLaunched

# 一些没用的初始化代码
# ...

async def send():
    await app.sendGroupMessage(group, MessageChain.create([
        Image.fromLocalFile(f"1.jpg")
    ]))

@bcc.receiver(ApplicationLaunched)
async def init():
    asyncio.create_task(send())

app.launch_blocking()
```

**控制台日志输出截图:**

`mirai-console` 无相关输出。

`graia-application`：

```python3
2021-06-19 21:49:40 racknerd-123456 asyncio[756782] ERROR Task exception was never retrieved
future: <Task finished name='Task-8' coro=<send() done, defined at ./qq-temp.py:39> exception=KeyError('json')>
Traceback (most recent call last):
  File "./qq-temp.py", line 41, in send
    await app.sendGroupMessage(group, MessageChain.create([
  File "/usr/local/lib/python3.8/dist-packages/graia/application/__init__.py", line 67, in wrapped_network_action_callable
    return await network_action_callable(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/graia/application/utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/graia/application/__init__.py", line 630, in sendGroupMessage
    message_result = await message.build()
  File "/usr/local/lib/python3.8/dist-packages/graia/application/message/chain.py", line 223, in build
    await run_always_await(
  File "/usr/local/lib/python3.8/dist-packages/graia/broadcast/utilles.py", line 23, in run_always_await
    return await any_callable
  File "/usr/local/lib/python3.8/dist-packages/graia/application/message/elements/internal.py", line 216, in toExternal
    return await app.uploadImage(
  File "/usr/local/lib/python3.8/dist-packages/graia/application/__init__.py", line 67, in wrapped_network_action_callable
    return await network_action_callable(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/graia/application/utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/graia/application/__init__.py", line 509, in uploadImage
    async with self.session.post(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 444, in _request
    await trace.send_request_start(method, url, headers)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/tracing.py", line 336, in send_request_start
    return await self._trace_config.on_request_start.send(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/signals.py", line 34, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/graia/application/test/request_tracing.py", line 26, in on_request_start
    f"Request[{req_id}:POST]: {params.url} using [{trace_config_ctx.trace_request_ctx[1]['json'] if trace_config_ctx.trace_request_ctx else None}]"
KeyError: 'json'
```

**运行环境:**
 - 操作系统: Linux(Ubuntu 20.04.2 LTS x86_64)
 - `mirai-core` 版本: 2.6.7
 - `mirai-api-http` 版本: 1.10.0
 - `graia-application-mirai` 版本: 0.19.0
 - 是否出现在机器人长期运行后: 否

**额外信息:**

* 已尝试过 #39 里的 `with enter_context(app=app)` 方法，没有任何影响
* 即使在启动很久后尝试发送图片，仍然会得到该错误
* `pydantic` 库版本为 `1.7.1`，应该不是该库的问题

**Comment by GreyElaina** [comment]
。。。log出的问题 hmmm

**Comment by GreyElaina** [comment]
关掉debug

**Comment by cutekibry** [comment]
> 关掉debug

解决了（草），想都想不到是 Log 问题
