### ISSUE TITLE
mcl可以登录，但是graia无法链接

### ISSUE THREAD

**Issue by gogolrq** [GraiaProject/Application#136]
mcl 1.0.5可以接受消息，但是graia （最新版本）链接不上。

(test) G:\QQbot\TongTu>python testtong.py
[2021-06-20 01:18:33,460][INFO]: initializing app...
Traceback (most recent call last):
  File "testtong.py", line 28, in <module>
    app.launch_blocking()
  File "G:\Anaconda\envs\test\lib\site-packages\graia\application\__init__.py", line 1613, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "G:\Anaconda\envs\test\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "G:\Anaconda\envs\test\lib\site-packages\graia\application\__init__.py", line 1503, in initialize
    await self.authenticate()
  File "G:\Anaconda\envs\test\lib\site-packages\graia\application\utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "G:\Anaconda\envs\test\lib\site-packages\graia\application\__init__.py", line 304, in authenticate
    response.raise_for_status()
  File "G:\Anaconda\envs\test\lib\site-packages\aiohttp\client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://localhost:8080/auth')

再三确认，key什么都是对的。

**Comment by gogolrq** [comment]
MCL消息

01:14:48 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" version 1.64
 01:14:49 [ERROR] Invalid update channel "nightly" for Package "bcprov-jdk15on"
 01:14:49 [INFO] Verifying "net.mamoe:mirai-console" version 2.7-M1
 01:14:49 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.7-M1
 01:14:50 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.7-M1
2021-06-20 01:14:52 I/main: Starting mirai-console...
2021-06-20 01:14:52 I/main: Backend: version 2.7-M1, built on 2021-06-19 13:21:33.
2021-06-20 01:14:52 I/main: Frontend Terminal: version 2.7-M1, provided by Mamoe Technologies
2021-06-20 01:14:52 I/main: Welcome to visit https://mirai.mamoe.net/
2021-06-20 01:14:52 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http
2021-06-20 01:14:52 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-06-20 01:14:52 I/Mirai HTTP API: ********************************************************
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2021-06-20 01:14:52 I/http adapter: >>> [http adapter] is listening at http://localhost:8080
2021-06-20 01:14:52 I/Mirai HTTP API: Http api server is running with verifyKey: test123
2021-06-20 01:14:52 I/Mirai HTTP API: adaptors: [http]
2021-06-20 01:14:52 I/Mirai HTTP API: ********************************************************
2021-06-20 01:14:52 I/main: 1 plugin(s) enabled.
2021-06-20 01:14:52 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2021-06-20 01:14:52 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2021-06-20 01:14:52 I/main: Auto-login 1844838249
2021-06-20 01:14:53 I/Bot.1844838249: [AccountSecretsManager] Loaded account secrets from local cache.
2021-06-20 01:14:54 I/Bot.1844838249: [AccountSecretsManager] Saved account secrets to local cache for fast login.
2021-06-20 01:14:54 I/Bot.1844838249: Login successful.
2021-06-20 01:14:56 V/Bot.1844838249: Event: BotOnlineEvent(bot=Bot(1844838249))
2021-06-20 01:14:56 I/Bot.1844838249: Bot login successful.
2021-06-20 01:14:56 I/main: mirai-console started successfully.

**Comment by Lzhjk1** [comment]
Mirai http api那边从1.X到2.X改了东西了
可以换回旧版本
在MCL根目录的config.json里
把几个beta都改成stable
再换回旧的http插件

**Comment by gogolrq** [comment]
> Mirai http api那边从1.X到2.X改了东西了
> 可以换回旧版本
> 在MCL根目录的config.json里
> 把几个beta都改成stable
> 再换回旧的http插件

多谢老哥，可以了
