### ISSUE TITLE
直接pip安装的包，有编译错误

### ISSUE THREAD

**Issue by Moyulingjiu** [GraiaProject/Application#140]
Traceback (most recent call last):
  File "************", line 4, in <module>
    from graia.application.entry import (
  File "************\lib\site-packages\graia\application\__init__.py", line 1646
    sync def getGroupFileList(self, group: Union[Group, int], path: Optional[str] = None) -> List[FileList]:
    ^
SyntaxError: invalid syntax

没什么复现步骤，就是async少了个a，把a加上后就可以运行。
起初我以为是自己版本的问题，后面删除缓存通过pip重新安装多遍，每一遍均出现了这个问题。
感觉应该只是粗心了一下吧23333

**Comment by GreyElaina** [comment]
不是我粗心，是提pr的。
0.19.2今晚发
