### ISSUE TITLE
cannot import name 'Protocol'

### ISSUE THREAD

**Issue by zhu2014yi** [GraiaProject/Application#150]
你好，我遇到了如标题的问题，我的库版本是如下，请问我应该如何解决!
Traceback (most recent call last):
  File "F:/Python_proj/Robot_transfer_msg/QQMsgTransfer/testRobot.py", line 1, in <module>
    from graia.broadcast import Broadcast
  File "D:\ProgramData\Anaconda3\envs\robot\lib\site-packages\graia\broadcast\__init__.py", line 8, in <module>
    from .builtin.event import ExceptionThrowed
  File "D:\ProgramData\Anaconda3\envs\robot\lib\site-packages\graia\broadcast\builtin\event.py", line 4, in <module>
    from ..entities.event import Dispatchable
  File "D:\ProgramData\Anaconda3\envs\robot\lib\site-packages\graia\broadcast\entities\event.py", line 2, in <module>
    from typing import TYPE_CHECKING, Any, Protocol, Tuple, TypeVar, Union
ImportError: cannot import name 'Protocol'
[image](https://user-images.githubusercontent.com/42707205/125932349-cb51595c-a444-46b0-8680-ef938853121d.png)

**Comment by zhu2014yi** [comment]
# packages in environment at D:\ProgramData\Anaconda3\envs\robot:
#
# Name                    Version                   Build  Channel
aiohttp                   3.7.4.post0              pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
certifi                   2021.5.30        py36haa95532_0
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.2                    pypi_0    pypi
contextvars               2.4                      pypi_0    pypi
dataclasses               0.8                      pypi_0    pypi
graia-application-mirai   0.20.1                   pypi_0    pypi
graia-broadcast           0.11.3                   pypi_0    pypi
idna                      3.2                      pypi_0    pypi
idna-ssl                  1.1.0                    pypi_0    pypi
immutables                0.15                     pypi_0    pypi
multidict                 5.1.0                    pypi_0    pypi
pip                       21.1.3           py36haa95532_0
pydantic                  1.8.2                    pypi_0    pypi
python                    3.6.13               h3758d61_0
regex                     2020.11.13               pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
setuptools                52.0.0           py36haa95532_0
sqlite                    3.36.0               h2bbff1b_0
typing-extensions         3.10.0.0                 pypi_0    pypi
urllib3                   1.26.6                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2              py36h7fe50ca_0
yarl                      1.6.3                    pypi_0    pypi
这是我的库的版本

**Comment by zhu2014yi** [comment]
下面是我的库的版本
packages in environment at D:\ProgramData\Anaconda3\envs\robot:
Name                    Version                   Build  Channel
aiohttp                   3.7.4.post0              pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
certifi                   2021.5.30        py36haa95532_0
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.2                    pypi_0    pypi
contextvars               2.4                      pypi_0    pypi
dataclasses               0.8                      pypi_0    pypi
graia-application-mirai   0.20.1                   pypi_0    pypi
graia-broadcast           0.11.3                   pypi_0    pypi
idna                      3.2                      pypi_0    pypi
idna-ssl                  1.1.0                    pypi_0    pypi
immutables                0.15                     pypi_0    pypi
multidict                 5.1.0                    pypi_0    pypi
pip                       21.1.3           py36haa95532_0
pydantic                  1.8.2                    pypi_0    pypi
python                    3.6.13               h3758d61_0
regex                     2020.11.13               pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
setuptools                52.0.0           py36haa95532_0
sqlite                    3.36.0               h2bbff1b_0
typing-extensions         3.10.0.0                 pypi_0    pypi
urllib3                   1.26.6                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2              py36h7fe50ca_0
yarl                      1.6.3                    pypi_0    pypi

**Comment by zhu2014yi** [comment]
已解决，版本不匹配，退回graia-application-maria==0.19版本就OK了
