### ISSUE TITLE
运行文档中例程时报错：TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by Mavacer** [GraiaProject/Application#153]
**描述你遇到的问题:**
运行文档中的例程时报错

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 使用poetry安装graia-application-mirai
2. 修正lifecycle.py中对BaseDispathcer的引用
3. poetry run python 运行文档中提到的例程(已将authKey修改为verifyKey）

**发生错误的代码**

**控制台日志输出截图:**

{'beforeDispatch': [], 'afterDispatch': [], 'beforeExecution': [], 'afterExecution': [], 'beforeTargetExec': [], 'afterTargetExec': []}
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/graia/graia/hello_world.py", line 12, in <module>
    app = GraiaMiraiApplication(
  File "/data/data/com.termux/files/home/.cache/pypoetry/virtualenvs/graia-ZKzXdU8U-py3.9/lib/python3.9/site-packages/graia/application/__init__.py", line 200, in __init__
    self.broadcast.dispatcher_interface.inject_global_raw(
  File "/data/data/com.termux/files/home/.cache/pypoetry/virtualenvs/graia-ZKzXdU8U-py3.9/lib/python3.9/site-packages/graia/broadcast/interfaces/dispatcher.py", line 114, in inject_global_raw
    self.flush_lifecycle_refs(dispatchers)
  File "/data/data/com.termux/files/home/.cache/pypoetry/virtualenvs/graia-ZKzXdU8U-py3.9/lib/python3.9/site-packages/graia/broadcast/interfaces/dispatcher.py", line 88, in flush_lifecycle_refs
    self.get_lifecycle_refs(dispatcher, lifecycle_refs)
TypeError: unhashable type: 'dict'
[2021-07-22 14:20:46,019][ERROR]: Unclosed client session
**运行环境:**
 - 操作系统: 在ubuntu18.04、termux上复现
 - `mirai-core` 版本: 未涉及
 - `mirai-api-http` 版本: 未涉及
 - `graia-application-mirai` 版本: 0.20.1
 - 是否出现在机器人长期运行后: 否

[**额外信息:**]

**Comment by karakoo** [comment]
这是bcc的问题，可以先回退版本
#147
