### ISSUE TITLE
运行bot.py报错：远程主机拒绝连接

### ISSUE THREAD

**Issue by Wdam** [GraiaProject/Application#163]
**描述你遇到的问题:**

在powershell中运行` python bot.py`时报错
**bot.py内容**
~~~
from graia.broadcast import Broadcast
from graia.application import GraiaMiraiApplication, Session
from graia.application.message.chain import MessageChain
import asyncio

from graia.application.message.elements.internal import Plain
from graia.application.friend import Friend

loop = asyncio.get_event_loop()

bcc = Broadcast(loop=loop)
app = GraiaMiraiApplication(
    broadcast=bcc,
    connect_info=Session(
        host="http://localhost:8080", # 填入 httpapi 服务运行的地址
        authKey="INI******7iG4D", # 填入 authKey
        account=1*******3627, # 你的机器人的 qq 号
        websocket=True # Graia 已经可以根据所配置的消息接收的方式来保证消息接收部分的正常运作.
    )
)

@bcc.receiver("FriendMessage")
async def friend_message_listener(app: GraiaMiraiApplication, friend: Friend):
    await app.sendFriendMessage(friend, MessageChain.create([
        Plain("Hello, World!")
    ]))

app.launch_blocking()
~~~
**net.mamoe.mirai-api-http的setting.yml**
~~~
cors: 
  - '*'
host: 0.0.0.0
port: 8080
authKey: INITKEY5kure0XY
cacheSize: 4096
enableWebsocket: true
report: 
  enable: false
  groupMessage: 
    report: true
  friendMessage: 
    report: true
  tempMessage: 
    report: true
  eventMessage: 
    report: true
  destinations: []
  extraHeaders: {}

heartbeat: 
  enable: false
  delay: 1000
  period: 15000
  destinations: []
  extraBody: {}

  extraHeaders: {}

~~~

**发生错误的代码**

~~~
PS E:\qqbot> python bot.py
[2021-08-11 17:14:45,832][INFO]: initializing app...
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\aiohttp\connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "D:\Python\lib\asyncio\base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "D:\Python\lib\asyncio\base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "D:\Python\lib\asyncio\base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\Python\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
  File "D:\Python\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "D:\Python\lib\asyncio\windows_events.py", line 599, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\qqbot\bot.py", line 28, in <module>
    app.launch_blocking()
  File "D:\Python\lib\site-packages\graia\application\__init__.py", line 1613, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "D:\Python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Python\lib\site-packages\graia\application\__init__.py", line 1503, in initialize
    await self.authenticate()
  File "D:\Python\lib\site-packages\graia\application\utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "D:\Python\lib\site-packages\graia\application\__init__.py", line 301, in authenticate
    async with self.session.post(
  File "D:\Python\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "D:\Python\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "D:\Python\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\Python\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\Python\lib\site-packages\aiohttp\connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "D:\Python\lib\site-packages\aiohttp\connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\Python\lib\site-packages\aiohttp\connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [远程计算机拒绝网络连 接。]
~~~
**控制台日志输出截图:**

![image](https://user-images.githubusercontent.com/42366809/129004411-a30915da-994c-4d4f-a976-5f2ad90b3b89.png)
**红色报错和本项目无关，不明原因，不影响使用**
![image](https://user-images.githubusercontent.com/42366809/129004550-53638d1a-0c81-4d9e-adad-e26a550a5db5.png)

**运行环境:**
 - 操作系统: 
 - windows 10专业版
 - `mirai-core` 版本: 
 - Mirai Console Loader version 1.1.0-bb5800f
 - `mirai-api-http` 版本: 
 - "net.mamoe:mirai-api-http" version 1.10.0
 - `graia-application-mirai` 版本: 
 - 执行`pip install graia-application-mirai`后的信息如下
![image](https://user-images.githubusercontent.com/42366809/129005553-274f29a4-c53c-432b-a095-60cf0d42b17b.png)

 - 是否出现在机器人长期运行后: 
否
**额外信息:**

~~~
C:\windows\system32>pip install graia-application-mirai
Requirement already satisfied: graia-application-mirai in d:\python\lib\site-packages (0.19.2)
Requirement already satisfied: pydantic<2.0.0,>=1.6.1 in d:\python\lib\site-packages (from graia-application-mirai) (1.7.1)
Requirement already satisfied: graia-broadcast<0.9.0,>=0.8.0 in d:\python\lib\site-packages (from graia-application-mirai) (0.8.11)
Requirement already satisfied: aiohttp<4.0.0,>=3.6.2 in d:\python\lib\site-packages (from graia-application-mirai) (3.7.4.post0)
Requirement already satisfied: regex<2021.0.0,>=2020.7.14 in d:\python\lib\site-packages (from graia-application-mirai) (2020.11.13)
Requirement already satisfied: yarl<2.0.0,>=1.4.2 in d:\python\lib\site-packages (from graia-application-mirai) (1.6.3)
Requirement already satisfied: async-timeout<4.0,>=3.0 in d:\python\lib\site-packages (from aiohttp<4.0.0,>=3.6.2->graia-application-mirai) (3.0.1)
Requirement already satisfied: chardet<5.0,>=2.0 in d:\python\lib\site-packages (from aiohttp<4.0.0,>=3.6.2->graia-application-mirai) (4.0.0)
Requirement already satisfied: typing-extensions>=3.6.5 in d:\python\lib\site-packages (from aiohttp<4.0.0,>=3.6.2->graia-application-mirai) (3.10.0.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\python\lib\site-packages (from aiohttp<4.0.0,>=3.6.2->graia-application-mirai) (5.1.0)
Requirement already satisfied: attrs>=17.3.0 in d:\python\lib\site-packages (from aiohttp<4.0.0,>=3.6.2->graia-application-mirai) (21.2.0)
Requirement already satisfied: iterwrapper<0.2.0,>=0.1.2 in d:\python\lib\site-packages (from graia-broadcast<0.9.0,>=0.8.0->graia-application-mirai) (0.1.4)
Requirement already satisfied: idna>=2.0 in d:\python\lib\site-packages (from yarl<2.0.0,>=1.4.2->graia-application-mirai) (3.2)
WARNING: You are using pip version 21.1.3; however, version 21.2.2 is available.
You should consider upgrading via the 'd:\python\python.exe -m pip install --upgrade pip' command.
~~~

**Comment by SiriusNEO** [comment]
https://github.com/project-mirai/mirai-api-http/issues/435

**Comment by skommando** [comment]
请问有进展吗，遇到一样的情况。windows 10专业版。
mah-1.2.2
mirai-core-all/mirai-console/mirai-console-terminal - 2.7.0
garia-application-mirai-0.19.2
启动 mcl 无error无warning，bot.py 运行报 aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8081 ssl:default [远程计算机拒绝网络连接。]

**Comment by skommando** [comment]
新鲜出炉，解决了，应该是 由于不明原因导致 mah 没有跟 mcl 关联上，以下是刚才的操作：
0、config.json 中无 mah 的配置，但是已有 /plugins/mah-1.12.0.jar。
1、运行 ./mcl --update-package net.mamoe:mirai-api-http --channel stable --type plugin & ./mcl，提示由于网络原因无法下载，本地 mah 文件损坏(file xxx corrupted)。
2、手工下载 https://github.com/project-mirai/mirai-api-http/releases/download/v1.12.0/mirai-api-http-v1.12.0.mirai.jar，移到 /plugins。
3、config.json 中移除 mah 配置。
4、运行 ./mcl，再运行 bot.py 无异常。
最终 config.json：
![image](https://user-images.githubusercontent.com/22767889/153732292-eed9c595-0908-437a-8b8b-360e0f2fceff.png)

**Comment by Wdam** [comment]
@skommando 没解决，直接不用了

**Comment by BlueGlassBlock** [comment]
> @skommando 没解决，直接不用了

See #177

**Comment by LnksW** [comment]
> > @skommando 没解决，直接不用了
> 
> See #177

主要是没时间折腾了

**Comment by GreyElaina** [comment]
换用 Ariadne(v4+)
