### ISSUE TITLE
握手失败，是否因为localhost地址和端口相关的原因

### ISSUE THREAD

**Issue by bowielab76** [GraiaProject/Application#164]
似乎是和localhost之间的通讯出现了问题，不确定是否是因为settings.yml和bot.py之间的设置有误。

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. My settings for http are: 
```
adapters:
  - http
debug: false
enableVerify: true
verifyKey: hYR4ccgwTu #randomised for privacy purposes
singleMode: false
cacheSize: 4096
adapterSettings: {
http:
    host: localhost
    port: 8080
    cors: [*]
}
```

2. My bot.py settings:
```
app = GraiaMiraiApplication(
    broadcast=bcc,
    connect_info=Session(
        host="http://localhost:8080", 
        authKey="hYR4ccgwTu",
        account=(my bot account), 
        websocket=True 
    )
)
```

**发生错误的代码**
```
Traceback (most recent call last):
  File "/Users/username/Downloads/bot.py", line 29, in <module>
    app.launch_blocking()
  File "/usr/local/lib/python3.9/site-packages/graia/application/__init__.py", line 1613, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/graia/application/__init__.py", line 1503, in initialize
    await self.authenticate()
  File "/usr/local/lib/python3.9/site-packages/graia/application/utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/graia/application/__init__.py", line 304, in authenticate
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://localhost:8080/auth')
```

**控制台日志输出截图:**
![image](https://user-images.githubusercontent.com/88880860/129436172-c597d7b3-039d-4efe-8460-e9b78a0936e7.png)
![image](https://user-images.githubusercontent.com/88880860/129437393-87a36657-6b49-4fa5-bff0-ce26555f7e1c.png)

**运行环境:**
 - 操作系统: macOS Big Sur 11.4
 - `mirai-core` 版本: 2.7-M2
 - `mirai-api-http` 版本: 2.2.0
 - `graia-application-mirai` 版本: 0.19.2
 - 是否出现在机器人长期运行后: 否

**Comment by SiriusNEO** [comment]
https://github.com/project-mirai/mirai-api-http/issues/435

**Comment by HowcanoeWang** [comment]
遇到了同样的问题，mcl自动登陆QQ接受消息ok，使用python bot.py运行会得到https://github.com/project-mirai/mirai-api-http/issues/435这个拒绝链接，然后后台开着mcl再新命令行里使用python bot.py运行，就会得到这个404的错误

**Comment by Colsrch** [comment]
把 mirai-console版本换成2.5.0就好了
```
mcl --update-package net.mamoe:mirai-console --channel stable --version 2.5.0
```
