### ISSUE TITLE
请问一下如何发送json类的消息，谢谢啦

### ISSUE THREAD

**Issue by chenshenwei1998** [GraiaProject/Application#22]
作者大大想问一下如何发送json类的消息，我代码看了半天没搞清楚json消息如何构造....（plain和图片的构造都看懂了，弱鸡落泪），然后试了好久也没成功，谢谢啦

**Comment by GreyElaina** [comment]
``` python
class Json(InternalElement, ExternalElement):
    Json: str = Field(..., alias="json")
```

你需要:

``` python
import json

MessageChain.create([
    Json(Json=json.dumps({
        # 你的 json
    }))
])
```

你自己把这个 issue 关了

**Comment by chenshenwei1998** [comment]
> 根据:
> 
> ```python
> class Json(InternalElement, ExternalElement):
>     Json: str = Field(..., alias="json")
> ```
> 
> 你需要:
> 
> ```python
> import json
> 
> MessageChain.create([
>     Json(Json=json.dumps({
>         # 你的 json
>     }))
> ])
> ```
> 
> 你自己把这个 issue 关了

哦哦看懂了，谢谢啦！

**Comment by chenshenwei1998** [comment]
> 根据:
> 
> ```python
> class Json(InternalElement, ExternalElement):
>     Json: str = Field(..., alias="json")
> ```
> 
> 你需要:
> 
> ```python
> import json
> 
> MessageChain.create([
>     Json(Json=json.dumps({
>         # 你的 json
>     }))
> ])
> ```
> 
> 你自己把这个 issue 关了

试了一下好像不行欸
如果这么写
```
from graia.application.entry import Image, Json, MessageChain
import json

music_json = {
	"app": "com.tencent.structmsg",
	"config":
	以下省略n字
}

await app.sendGroupMessage(group, MessageChain.create([Json(Json=json.dumps(music_json))]))
```

会抛出
```
Traceback (most recent call last):
  File "bot.py", line 130, in group_message_handler
    await app.sendGroupMessage(group, MessageChain.create([Json(Json=json.dumps(music_json))]))
  File "pydantic\main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Json
json
  field required (type=value_error.missing)
```
  
然后我把Json换成别名json，
`await app.sendGroupMessage(group, MessageChain.create([Json(json=json.dumps(music_json))]))`

又会抛出
```
Traceback (most recent call last):
  File "bot.py", line 130, in group_message_handler
    await app.sendGroupMessage(group, MessageChain.create([Json(json=json.dumps(music_json))]))
  File "D:\software\anaconda3\lib\site-packages\graia\application\__init__.py", line 205, in sendGroupMessage
    response.raise_for_status()
  File "D:\software\anaconda3\lib\site-packages\aiohttp\client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://localhost:8988/sendGroupMessage')
```

这是怎么回事啊QAQ

**Comment by GreyElaina** [comment]
附带 mirai-console 输出.

**Comment by chenshenwei1998** [comment]
> 附带 mirai-console 输出.

用的是miraiOK，并没有什么输出TAT

**Comment by chenshenwei1998** [comment]
> 附带 mirai-console 输出.

我在application包里添加了print((await message.build()).dict()['__root__'])的输出，发现是post的格式问题，应该是个bug
输出信息如下
```
# 下面这条是文本的post信息中的messagechain的值，格式是正确的
[{'type': 'Plain', 'text': '你好哇，很开心你能找我聊天。'}]
# 下面这条是json的post信息中的messagechain的值，格式有误
[{'json': '{"app": "com.tencent.structmsg"}'}]
Traceback (most recent call last):
  File "bot.py", line 140, in group_message_handler
    await app.sendGroupMessage(group, MessageChain.create([Json(json=json.dumps(music_json_str))]))
  File "D:\software\anaconda3\lib\site-packages\graia\application\__init__.py", line 207, in sendGroupMessage
    response.raise_for_status()
  File "D:\software\anaconda3\lib\site-packages\aiohttp\client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://localhost:8988/sendGroupMessage')
```

**Comment by GreyElaina** [comment]
已知: FlashImage, Poke 等都有此种bug 需要修复.

**Comment by GreyElaina** [comment]
更新到 0.1.3 尝试修复该错误

**Comment by chenshenwei1998** [comment]
> 更新到 0.1.3 尝试修复该错误

问题已修复，非常感谢！
