### ISSUE TITLE
在mirai-console报错重启后 ，graia-application 不再能接收消息

### ISSUE THREAD

**Issue by aboutmydreams** [GraiaProject/Application#28]
**描述你遇到的问题:**
最近经常出现收不到消息的情况，今天专门去console看下啥情况，发现在mirai-console报错重启后 ，graia-application 不再能接收消息，但是mirai-console重启后是可以看到打印消息的

**复现步骤:**
该 BUG 会在进行以下操作后出现:
加入较多群（20个左右，其中5个比较火热）

**控制台日志输出截图:**
```
 11:13:55 [INFO] [BOT 3539347852] [❤群(123123)] Thaumiel(321321321) -> [mirai:source:650897,1066985371]**奶茶**
 11:14:03 [INFO] [NETWORK] Send: Heartbeat.Alive
 11:14:03 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 11:14:10 [INFO] [BOT 3539347852] [❤群(123123)] 弟四号(321321879) -> [mirai:source:650898,2133225292][mirai:image:{1C311994-AA32-7E30-689C-929B150BE4B0}.mirai]
 11:15:03 [INFO] [NETWORK] Send: Heartbeat.Alive
 11:15:03 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 11:15:10 [INFO] [BOT 123123123] [❤群(123123)] 学 长+我(123123123) -> [mirai:source:650899,-2064435564][mirai:image:{ADDAD040-FB69-60D9-C9E4-88A66D4266C0}.mirai] 
Exception in thread "DefaultDispatcher-worker-4" java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377)
        at io.ktor.utils.io.nio.ChannelsKt.read(Channels.kt:135)
        at io.ktor.network.sockets.CIOReaderKt$attachForReadingDirectImpl$1$1$1.invokeSuspend(CIOReader.kt:90)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:137)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:108)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:308)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:318)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
        at io.ktor.network.selector.SelectorManagerSupport.handleSelectedKey(SelectorManagerSupport.kt:84)
        at io.ktor.network.selector.SelectorManagerSupport.handleSelectedKeys(SelectorManagerSupport.kt:64)
        at io.ktor.network.selector.ActorSelectorManager.process(ActorSelectorManager.kt:73)
        at io.ktor.network.selector.ActorSelectorManager$process$1.invokeSuspend(ActorSelectorManager.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Exception in thread "DefaultDispatcher-worker-4" java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377)
        at io.ktor.utils.io.nio.ChannelsKt.read(Channels.kt:135)
        at io.ktor.network.sockets.CIOReaderKt$attachForReadingDirectImpl$1$1$1.invokeSuspend(CIOReader.kt:90)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:137)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:108)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:308)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:318)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
        at io.ktor.network.selector.SelectorManagerSupport.handleSelectedKey(SelectorManagerSupport.kt:84)
        at io.ktor.network.selector.SelectorManagerSupport.handleSelectedKeys(SelectorManagerSupport.kt:64)
        at io.ktor.network.selector.ActorSelectorManager.process(ActorSelectorManager.kt:73)
        at io.ktor.network.selector.ActorSelectorManager$process$1.invokeSuspend(ActorSelectorManager.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
 11:15:35 [INFO] [BOT 321123123] [❤群(123123)] 19 行管 河南 小吴(3219218293) -> [mirai:source:650900,1966226433]奶茶～
 11:16:03 [INFO] [NETWORK] Send: Heartbeat.Alive
 11:16:03 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
控制台恢复正常接收消息……
```

**graia-application 没有输出，只是终止打印收到的消息
最后一条打印的消息是 『奶茶』**（第一行）

**运行环境:**
 - 操作系统:  macos
 - mirai-core 版本:latest
 - mirai-api-http 版本:latest
 - graia-application-mirai 版本:0.1.1 (pip3 install)
 - 是否出现在机器人长期运行后: [否] 且经常出现

**Comment by GreyElaina** [comment]
![image](https://user-images.githubusercontent.com/31543961/89724597-d338e880-da37-11ea-84e7-c73107ee78d7.png)
![image](https://user-images.githubusercontent.com/31543961/89724599-db912380-da37-11ea-9aec-bd21cf9bd405.png)

?

边缘情况, 自行重启, 以后的版本优化

**Comment by aboutmydreams** [comment]
python 一定要3.7吗，我上午在linux服务器上跑同样的代码，刚刚检查了下使用的0.1.5的graia-application-mirai，发现跑起来后发消息没有打印（本来在代码里写了 `print(message.asDisplay())`  且mirai-console有输出消息）
![image](https://user-images.githubusercontent.com/34613360/89724651-77bb2a80-da38-11ea-8cab-f42520ea1228.png)

**Comment by aboutmydreams** [comment]
（linux服务器和我本地macos是3.8.5的python
