### ISSUE TITLE
通过http方式连接时fetchMessage出错

### ISSUE THREAD

**Issue by ssttkkl** [GraiaProject/Application#31]
**描述你遇到的问题:**
启动bot时抛出异常并直接退出
```
Traceback (most recent call last):
  File "C:/Users/---/PycharmProjects/PixivBot/bot.py", line 83, in <module>
    app.launch_blocking()
  File "C:\Users\---\PycharmProjects\PixivBot\.venv\lib\site-packages\graia\application\__init__.py", line 893, in launch_blocking
    loop.run_until_complete(fetch_method)
  File "C:\Users\---\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\Users\---\PycharmProjects\PixivBot\.venv\lib\site-packages\graia\application\__init__.py", line 844, in http_fetchmessage_poster
    data = await self.fetchMessage(fetch_num)
  File "C:\Users\---\PycharmProjects\PixivBot\.venv\lib\site-packages\graia\application\__init__.py", line 423, in fetchMessage
    result.append(await self.auto_parse_by_type(event))
  File "C:\Users\---\PycharmProjects\PixivBot\.venv\lib\site-packages\graia\application\__init__.py", line 810, in auto_parse_by_type
    if not original_dict.get("type") and not isinstance(original_dict.get("type"), str):
AttributeError: 'str' object has no attribute 'get'
```

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 使用`websocket=False`的方式初始化Session和GraiaMiraiApplication
2. `app.launch_blocking()`

**控制台日志输出截图:**
![TIM截图20200814141153](https://user-images.githubusercontent.com/17331698/90219234-2811a000-de38-11ea-8a06-58a6ac6e1925.png)

**运行环境:**
 - 操作系统: Windows
 - `mirai-core` 版本: 0.5.2
 - `mirai-api-http` 版本: 1.7.3
 - `graia-application-mirai` 版本: 0.1.10
 - 是否出现在机器人长期运行后: 否

**额外信息:**

**Comment by GreyElaina** [comment]
好了好了知道了.

**Comment by GreyElaina** [comment]
初始化 `GraiaMiraiApplication` 时加上 `debug=True`.

**Comment by GreyElaina** [comment]
?
