### ISSUE TITLE
messageFromId报错AttributeError: module ' graia. application. event' has no attribute 'get '

### ISSUE THREAD

**Issue by RiotGamesU** [GraiaProject/Application#41]
环境:
**mirai-console-1.0-M4.jar
mirai-console-pure-1.0-M4.jar
mirai-core-qqandroid-1.3.0.jar
mirai-api-http-v1.8.4.jar(mirai-api-http-v1.8.3.jar两个都测试过都这样)
graia最新版**

源码:
'quote1 = await app.messageFromId(message.get(Quote)[0].origin).get(Source)[0].id
# 还测试过:
# message.get(Quote)[0].id
# message.get(Quote)[0.origin.get(Source)[0]
# 都会报错`

输出:
Traceback (most recent call last):
File "C: \data1\P\Python\mirai1\venv\tib\site- packages \graia\broadcast\__ init__ py", line 163， in Executor
result = await run_ always_ await(
File "C: \data1\P\Python\mirai1 \venv\lib\site一packages \graia \broadcast\utilles.pY", line 10，in run_ always_ await
return await any_ callable
File "C:/data1/P/Python/mirai1/mirai1/bot1.py" Line 394， in group_ message_ handLer
quote1: GroupMessage = await app . messageFromId(message . get(Quote ) [@] . origin. get(Source)[@].id)
File "C: \data1\P\Python\mirai1\venv\Lib\site- packages\graia\application\utilles.py", line 15，in wrapper
return await func(self, *args， **kwargs )
File "C: \data1\P\Python\mirai1\venv\Lib\site -packages \graia \application\ . init__ .DY"， line 628， in messageFromId
return await self . auto . parse_ by_ type (event)
File "C: \data1\P\Python\mirai1\venv\liblsite-packages \graia\application\_ init__ 。 py", line 940， in auto_ parse_ by_ type
if not original_ dict.get("type") and not isinstance(originaL_ dict.get("type"), str):
AttributeError: module ' graia. application. event' has no attribute 'get '

**Comment by GreyElaina** [comment]
修了.
