### ISSUE TITLE
失踪的属性"app"

### ISSUE THREAD

**Issue by User-Hrsat** [GraiaProject/Application#51]
**描述你遇到的问题:**

> 似乎是意料之外的问题

**复现步骤:**
该 BUG 会在进行以下操作后出现:
- 当我运行一个GraiaMiraiApplication实例时

**发生错误的代码**

```python
@app.receiver("GroupMessage")
async def event_gm(mirai: GraiaMiraiApplication, message: MessageChain, group: Group, member: Member):

    messages = message.toString()                   #留做刷屏和脏话的检测
    timestamp = message.__root__[0].time            #每条消息的时间
    membernames = member.memberName
    memberid = member.id                            #发送消息的人

    command = Features.Clear(messages)              #清洗文本,提取指令

    switch = {                                      #switch/case
            'text' : Plain,                         #消息组件复用
            'image' : Image.fromFileSystem,         #消息组件复用
            'xml' : Xml,                     #消息组件复用
            ':网抑云' : Features.Cloudmusic,
            ':image' : Features.Image,
            ':rss' : Features.RSS,
            ':zuan' : Features.Zuan,
            ':help' : Features.Help,
            'analysis': Features.Analysis
        }

    async def sendmessage(i):

        try:
            if i == 'analysis':
                try:
                    getmessages, infotype = switch[i](timestamp, membernames, memberid, messages)
                except TypeError:
                    return
            else:
                getmessages, infotype = switch[i]()
        except KeyError:                            #需要参数或者匹配的
            if re.match('^:ping', i):
                getmessages, infotype = Features.Ping(i)
            else:
                return

        await mirai.sendGroupMessage(
                group.id,
                [
                    At(target=memberid),
                    switch[infotype](getmessages)
                    ]
                )

    for i in command:                               #经过清洗提取的指令会逐一运行
        await sendmessage(i)

if __name__ == "__main__":
    mirai.launch_blocking()
```

**控制台日志输出截图:**

> mirai-console那边没有问题
```txt
Traceback (most recent call last):
  File "Main.py", line 103, in <module>
    mirai.launch_blocking()
  File "/usr/lib/python3.8/site-packages/graia/application/__init__.py", line 1076, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/graia/application/__init__.py", line 997, in initialize
    self.broadcast.postEvent(ApplicationLaunched(self))
  File "/usr/lib/python3.8/site-packages/graia/application/event/lifecycle.py", line 9, in __init__
    self.app = app
AttributeError: 'ApplicationLaunched' object has no attribute 'app'
```

**运行环境:**
 - 操作系统: `Manjaro[Linux>Terminal>MiraiOK]`
 - `mirai-core` 版本: mirai-core-qqandroid-1.2.3
 - `mirai-api-http` 版本: v1.8.4
 - `graia-application-mirai` 版本: 0.10.10
 - 是否出现在机器人长期运行后: 否

**额外信息:**

> 快让我进Q群！
```txt
    我尝试过更改原app和mirai的实例名，但是无效
    看起来并不是与保留字冲突的原因
```

**Comment by mtuba** [comment]
我在参考官方文档 https://graia-document.vercel.app/ 的安装并配置开发环境时，运行 bot.py 也出现了同样的问题
`
root@VM-0-12-ubuntu:~/newLab# python3 bot.py 
[2020-10-28 17:34:39,904][INFO]: initializing app...
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    app.launch_blocking()
  File "/usr/local/lib/python3.8/dist-packages/graia/application/__init__.py", line 1076, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/graia/application/__init__.py", line 997, in initialize
    self.broadcast.postEvent(ApplicationLaunched(self))
  File "/usr/local/lib/python3.8/dist-packages/graia/application/event/lifecycle.py", line 9, in __init__
    self.app = app
AttributeError: 'ApplicationLaunched' object has no attribute 'app'
`

**Comment by mtuba** [comment]
我在参考官方文档 https://graia-document.vercel.app/ 的安装并配置开发环境时，运行 bot.py 也出现了同样的问题
**控制台日志输出截图:**

> root@VM-0-12-ubuntu:~/newLab# python3 bot.py 
[2020-10-28 17:31:03,004][INFO]: initializing app...
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    app.launch_blocking()
  File "/usr/local/lib/python3.8/dist-packages/graia/application/__init__.py", line 1076, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/graia/application/__init__.py", line 997, in initialize
    self.broadcast.postEvent(ApplicationLaunched(self))
  File "/usr/local/lib/python3.8/dist-packages/graia/application/event/lifecycle.py", line 9, in __init__
    self.app = app
AttributeError: 'ApplicationLaunched' object has no attribute 'app'

**运行环境:**

- 操作系统: ubuntu

- mirai-core 版本: mirai-core-qqandroid-1.2.3

- mirai-api-http 版本: v1.8.4
- graia-application-mirai 版本: 0.10.10
- 是否出现在机器人长期运行后: 否

**Comment by averitas** [comment]
遇到了一样的问题，ubuntu18.04，python版本3.8，在启动时报这个错误程序无法启动

**Comment by GreyElaina** [comment]
(来自开发者的迷惑)

**Comment by averitas** [comment]
问题出在pydantic包，graia.broadcast.entities.event.EventMeta类继承自pydantic中的ModelMetaclass类，在pydantic版本是1.7.1的情况下该类貌似添加了一个空的__slots__属性，导致子类都无法进行self的赋值。把pydantic包回退到1.6.1版本问题解决。

我对python了解不深，pydantic包的作用不是很清楚，还望指教。

**Comment by User-Hrsat** [comment]
似乎是这样！
这个问题留着吧！
