### ISSUE TITLE
文档示例运行失败

### ISSUE THREAD

**Issue by LuneZ99** [GraiaProject/Application#60]
**描述你遇到的问题:**
文档示例运行失败

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 使用文档中 历史性的第一次对话 的代码运行
2. 报错 graia.application.exceptions.AccountNotFound

**发生错误的代码**
```
from graia.broadcast import Broadcast
from graia.application import GraiaMiraiApplication, Session
from graia.application.message.chain import MessageChain
import asyncio

from graia.application.message.elements.internal import Plain
from graia.application.friend import Friend

loop = asyncio.get_event_loop()

bcc = Broadcast(loop=loop)
app = GraiaMiraiApplication(
    broadcast=bcc,
    connect_info=Session(
        host="http://localhost:8765", # 填入 httpapi 服务运行的地址（httpapi的config已经设置到了8765）
        authKey="*******AUTHKEY", # 填入 authKey
        account=3254******, # 你的机器人的 qq 号
        websocket=True # Graia 已经可以根据所配置的消息接收的方式来保证消息接收部分的正常运作.
    )
)

@bcc.receiver("FriendMessage")
async def friend_message_listener(app: GraiaMiraiApplication, friend: Friend):
    await app.sendFriendMessage(friend, MessageChain.create([
        Plain("Hello, World!")
    ]))

app.launch_blocking()

```

**控制台日志输出截图:**

mirai-console 控制台无额外输出

graia-application 输出

```

[2020-11-16 20:32:41,240][INFO]: initializing app...
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    app.launch_blocking()
  File "D:\Program Files\Python38\lib\site-packages\graia\application\__init__.py", line 1087, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "D:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "D:\Program Files\Python38\lib\site-packages\graia\application\__init__.py", line 994, in initialize
    await self.activeSession()
  File "D:\Program Files\Python38\lib\site-packages\graia\application\utilles.py", line 15, in wrapper
    return await func(self, *args, **kwargs)
  File "D:\Program Files\Python38\lib\site-packages\graia\application\__init__.py", line 189, in activeSession
    raise_for_return_code(data)
  File "D:\Program Files\Python38\lib\site-packages\graia\application\utilles.py", line 76, in raise_for_return_code
    raise exception_code
graia.application.exceptions.AccountNotFound

Process finished with exit code 1

```

**运行环境:**
 - 操作系统: Win10
 - `mirai-core` 版本: 1.2.3
 - `mirai-api-http` 版本: 1.8.4
 - `graia-application-mirai` 版本: 0.10.14
 - 是否出现在机器人长期运行后: 否，首次运行

**额外信息:**
尝试使用过新注册qq号、长期在本机登录的常用qq号、不常登录但已经注册了很久的小号，均报同样错误。

**Comment by GreyElaina** [comment]
............请问您看了注释了吗, 仔细看了文档了吗

*rubbish issue.*

**Comment by GreyElaina** [comment]
Account Not Found. 请确认你的 mirai-console 登录了账号/qq没填错

**Comment by LuneZ99** [comment]
重新确认了一下是在操作mirai-console之后那边出了问题，错过了那边的报错信息，抱歉。
