### ISSUE TITLE
群员被踢事件中如何获取被踢成员的信息（QQ）

### ISSUE THREAD

**Issue by cqx888** [GraiaProject/Application#65]
代码
```
@bcc.receiver("MemberLeaveEventKick")
async def member_leave_kick_listener(app: GraiaMiraiApplication, group: Group, member: Member):
    print("被踢事件")
    print(member)
```

群员被踢后报错：
```
Traceback (most recent call last):
  File "/Users/my-macbook-pro/Documents/qqbot/main/venv/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 240, in Executor
    await dii.lookup_param(name, annotation, default)
  File "/Users/my-macbook-pro/Documents/qqbot/main/venv/lib/python3.8/site-packages/graia/broadcast/interfaces/dispatcher.py", line 209, in lookup_param
    raise RequirementCrashed("the dispatching requirement crashed: ", self.name, self.annotation, self.default)
graia.broadcast.exceptions.RequirementCrashed: ('the dispatching requirement crashed: ', 'member', <class 'graia.application.group.Member'>, None)
```

**Comment by GreyElaina** [comment]
。。。看内置文档啊，这个因为有歧义, 如果是被踢的要把参数写成 "member: Member = 'target'", 操作者则是 'operator'.
