### ISSUE TITLE
TypeError: Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by Yan-Zero** [GraiaProject/Application#76]
**描述你遇到的问题:**
TypeError: Expected maxsize to be an integer or None
库的问题

**发生错误的代码**
就是那个 Hello World 的示例

**控制台日志输出截图:**
机器人哒：
2021-01-05 23:25:56 I/main: Starting mirai-console...
2021-01-05 23:25:56 I/main: Backend: version 2.0-M2, built on 2020-12-28 18:39:29.
2021-01-05 23:25:56 I/main: Frontend Terminal: version 2.0-M2, provided by Mamoe Technologies
2021-01-05 23:25:56 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http
2021-01-05 23:25:57 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-01-05 23:25:57 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2021-01-05 23:25:57 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 0.0.0.0:8080
2021-01-05 23:25:57 I/Mirai HTTP API: Http api server is running with authKey: 【脱敏】
2021-01-05 23:25:57 I/net.mamoe.mirai-api-http: 心跳模块启用状态: false
2021-01-05 23:25:57 I/net.mamoe.mirai-api-http: 上报模块启用状态: false
2021-01-05 23:25:57 I/main: 1 plugin(s) enabled.
2021-01-05 23:25:57 I/main: Auto-login 【脱敏】
2021-01-05 23:25:58 I/Bot.【脱敏】: Logging in...
2021-01-05 23:25:59 I/Bot.【脱敏】: Online OtherClients: 
2021-01-05 23:26:02 I/Bot.【脱敏】: Login successful
2021-01-05 23:26:02 I/main: mirai-console started successfully.

Python 哒：
Traceback (most recent call last):
  File "bot.py", line 4, in <module>
    from graia.broadcast import Broadcast
  File "/usr/local/lib/python3.7/dist-packages/graia/broadcast/__init__.py", line 23, in <module>
    from .typing import T_Dispatcher, T_Dispatcher_Callable
  File "/usr/local/lib/python3.7/dist-packages/graia/broadcast/typing.py", line 9, in <module>
    from graia.broadcast.entities.dispatcher import BaseDispatcher
  File "/usr/local/lib/python3.7/dist-packages/graia/broadcast/entities/dispatcher.py", line 46, in <module>
    from graia.broadcast.abstract.interfaces.dispatcher import IDispatcherInterface
  File "/usr/local/lib/python3.7/dist-packages/graia/broadcast/abstract/interfaces/dispatcher.py", line 29, in <module>
    class IDispatcherInterface(metaclass=ABCMeta):
  File "/usr/local/lib/python3.7/dist-packages/graia/broadcast/abstract/interfaces/dispatcher.py", line 90, in IDispatcherInterface
    ) -> Optional[Dict[str, List]]:
  File "/usr/lib/python3.7/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

**运行环境:**
 - 操作系统: Debian 10
 - `mirai-core` 版本: 2.0-M2
 - `mirai-api-http` 版本: 1.9.5
 - `graia-application-mirai` 版本: 0.14.1（刚安装哒）
 - `Python` 版本: 3.7.3

**Comment by GreyElaina** [comment]
更新 `graia-broadcast` 至最新版本解决问题
