### ISSUE TITLE
NotFoundError: No module named 'devtools'

### ISSUE THREAD

**Issue by RiotGamesU** [GraiaProject/Application#78]
Traceback (most recent call last):
  File "bot1.py", line 3, in <module>
    from graia.application import GraiaMiraiApplication, Session
  File "C:\Users\Administrator\Desktop\python382\lib\site-packages\graia\application\__init__.py", line 33, in <module>
    from graia.application.test.request_tracing import HttpRequestTracing
  File "C:\Users\Administrator\Desktop\python382\lib\site-packages\graia\application\test\request_tracing.py", line 9, in <module>
    from devtools import debug
ModuleNotFoundError: No module named 'devtools'

version:latest

**Comment by karakoo** [comment]
pip install devtools
