### ISSUE TITLE
TypeError: A single constraint is not allowed 

### ISSUE THREAD

**Issue by Peiiii** [GraiaProject/Application#85]
**TypeError: A single constraint is not allowed :**

**发生错误的代码**
在文件graia.application.message.chain.py中，第24行
T = TypeVar("T", Type[Element])
此行代码在python3.7下报错
经测试，将其修改为T=Element后可正常运行

**报错信息:**
Traceback (most recent call last):
  File "D:/Projects/PythonProjects/loveSource/bot.py", line 2, in <module>
    from graia.application import GraiaMiraiApplication, Session
  File "D:\programs\python\lib\site-packages\graia\application\__init__.py", line 37, in <module>
    from .event.messages import FriendMessage, GroupMessage, TempMessage
  File "D:\programs\python\lib\site-packages\graia\application\event\messages.py", line 3, in <module>
    from graia.application.event.dispatcher import MessageChainCatcher
  File "D:\programs\python\lib\site-packages\graia\application\event\dispatcher.py", line 3, in <module>
    from graia.application.message.chain import MessageChain
  File "D:\programs\python\lib\site-packages\graia\application\message\chain.py", line 24, in <module>
    T = TypeVar("T", Type[Element])
  File "D:\programs\python\lib\typing.py", line 543, in __init__
    raise TypeError("A single constraint is not allowed")
TypeError: A single constraint is not allowed

**运行环境:**
 - python3.7

**Comment by GreyElaina** [comment]
太正常了, 等我改改
