### ISSUE TITLE
运行bot.py后报错，invalid syntax

### ISSUE THREAD

**Issue by Wushengyao** [GraiaProject/Application#98]
**描述你遇到的问题:**
按照教程中编写bot.py并尝试运行，报invalid syntax错误

**发生错误的代码**
(mypython) C:\Users\wushengyao\Desktop\Tutorial\提交版v0.2\QQBot>python bot.py
Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    from graia.application import GraiaMiraiApplication, Session
  File "D:\Users\wushengyao\anaconda3\envs\mypython\lib\site-packages\graia\application\__init__.py", line 35, in <module>
    from graia.application.test.request_tracing import HttpRequestTracing
  File "<fstring>", line 1
    (await params.response.text())
                ^
SyntaxError: invalid syntax

**Comment by Wushengyao** [comment]
![image](https://user-images.githubusercontent.com/57943174/108806337-63a5d780-75dc-11eb-99d7-1c95aea67a75.png)

**Comment by Wushengyao** [comment]
mirai-console状态
![image](https://user-images.githubusercontent.com/57943174/108806554-fb0b2a80-75dc-11eb-89b3-6d829abc273d.png)

**Comment by Wushengyao** [comment]
解决了，换成python3.7就好了。
